name: ssonny
services:
  postgres:
    container_name: postgres
    env_file: configs/ignore-postgres.env
    networks:
      - local_network
    volumes:
      - pgdata:/var/lib/postgresql/data
    image: postgres:16.2-alpine3.19
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 2s
      retries: 8
  migrate:
    depends_on:
      postgres:
        condition: service_healthy
    env_file: configs/ignore-postgres.env
    networks:
      - local_network
    volumes:
      - ./migrations:/migrations:ro
    build:
      context: .
      dockerfile: Dockerfile-migrate
  service:
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - 8080:8080
    networks:
      - local_network
    volumes:
      - ./configs:/config:ro
    build: .
networks:
  local_network:
  global_network:
    external: true
volumes:
  pgdata: