// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Onnywrite/ssonny/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	repo "github.com/Onnywrite/ssonny/internal/storage/repo"
)

// SessionRepo is an autogenerated mock type for the SessionRepo type
type SessionRepo struct {
	mock.Mock
}

type SessionRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepo) EXPECT() *SessionRepo_Expecter {
	return &SessionRepo_Expecter{mock: &_m.Mock}
}

// SaveSession provides a mock function with given fields: _a0, _a1
func (_m *SessionRepo) SaveSession(_a0 context.Context, _a1 models.Session) (repo.Transactor, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveSession")
	}

	var r0 repo.Transactor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Session) (repo.Transactor, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Session) repo.Transactor); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Transactor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Session) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionRepo_SaveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSession'
type SessionRepo_SaveSession_Call struct {
	*mock.Call
}

// SaveSession is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 models.Session
func (_e *SessionRepo_Expecter) SaveSession(_a0 interface{}, _a1 interface{}) *SessionRepo_SaveSession_Call {
	return &SessionRepo_SaveSession_Call{Call: _e.mock.On("SaveSession", _a0, _a1)}
}

func (_c *SessionRepo_SaveSession_Call) Run(run func(_a0 context.Context, _a1 models.Session)) *SessionRepo_SaveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Session))
	})
	return _c
}

func (_c *SessionRepo_SaveSession_Call) Return(_a0 repo.Transactor, _a1 error) *SessionRepo_SaveSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionRepo_SaveSession_Call) RunAndReturn(run func(context.Context, models.Session) (repo.Transactor, error)) *SessionRepo_SaveSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionRepo creates a new instance of SessionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepo {
	mock := &SessionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
