// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Transactor is an autogenerated mock type for the Transactor type
type Transactor struct {
	mock.Mock
}

type Transactor_Expecter struct {
	mock *mock.Mock
}

func (_m *Transactor) EXPECT() *Transactor_Expecter {
	return &Transactor_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function with given fields:
func (_m *Transactor) Commit() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Transactor_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type Transactor_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *Transactor_Expecter) Commit() *Transactor_Commit_Call {
	return &Transactor_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *Transactor_Commit_Call) Run(run func()) *Transactor_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Transactor_Commit_Call) Return(_a0 error) *Transactor_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Transactor_Commit_Call) RunAndReturn(run func() error) *Transactor_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields:
func (_m *Transactor) Rollback() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Transactor_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type Transactor_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
func (_e *Transactor_Expecter) Rollback() *Transactor_Rollback_Call {
	return &Transactor_Rollback_Call{Call: _e.mock.On("Rollback")}
}

func (_c *Transactor_Rollback_Call) Run(run func()) *Transactor_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Transactor_Rollback_Call) Return(_a0 error) *Transactor_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Transactor_Rollback_Call) RunAndReturn(run func() error) *Transactor_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactor creates a new instance of Transactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Transactor {
	mock := &Transactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
