# example-sso.yaml is an example configuration file for the SSO service.

# TLS configuration.
# Paths must be either absolute or relative to the current file.
tls:
  # certPath is the path to the TLS certificate file.
  # Can be overriden by TLS_CERT_PATH environment variable.
  # Default is /etc/sso/tls.crt to be comfortable to use with kubernetes.
  certPath: example-cert.pem
  # keyPath is the path to the TLS key file.
  # Can be overriden by TLS_KEY_PATH environment variable.
  # Default is /etc/sso/tls.key to be comfortable to use with kubernetes.
  keyPath: example-key.pem

# Secrets configuration
secrets:
  # postgres holds the configuration for connecting to the PostgreSQL database.
  postgres:
    # host is the hostname or IP address of the PostgreSQL server.
    # Can be overriden by POSTGRES_HOST environment variable.
    host: postgres 
    # port is the port number of the PostgreSQL server.
    # Can be overriden by POSTGRES_PORT environment variable.
    # Default is 5432.
    port: 5432
    # user is the username for connecting to the PostgreSQL database.
    # Can be overriden by POSTGRES_USER environment variable.
    user: username
    # password is the password for connecting to the PostgreSQL database.
    # Can be overriden by POSTGRES_PASS environment variable.
    password: user_password
    # database is the name of the PostgreSQL database to connect to.
    # Can be overriden by POSTGRES_DB environment variable.
    database: database
    # sslmode specifies whether to use SSL/TLS for connecting to the PostgreSQL database.
    # Can be overriden by POSTGRES_SSL environment variable.
    # Default is disable.
    sslmode: disable
  # redis holds the configuration for connecting to the Redis server.
  redis:
    # host is the hostname or IP address of the Redis server.
    # Can be overriden by REDIS_HOST environment variable.
    host: redis
    # port is the port number of the Redis server.
    # Can be overriden by REDIS_PORT environment variable.
    # Default is 6379.
    port: 6379
    # user is the username for connecting to the Redis server.
    # Can be overriden by REDIS_USER environment variable.
    user: default
    # password is the password for connecting to the Redis server.
    # Can be overriden by REDIS_PASS environment variable.
    password: user_password
    # db is the database number to connect to on the Redis server.
    # Can be overriden by REDIS_DB environment variable.
    db: 0
  # secretString is a secret string used by the application.
  # Can be overriden by SECRET_STRING environment variable.
  secretString: our_big_secret

# HTTP server configuration.
http:
  # port is the port number that the HTTP server will listen on.
  # Can be overriden by HTTP_PORT environment variable.
  # Default is 8080.
  port: 8080
  # useTls specifies whether to use TLS for the HTTP server.
  # Can be overriden by HTTP_USE_TLS environment variable.
  # Default is false.
  useTls: false

# gRPC server configuration.
grpc:
  # port is the port number that the gRPC server will listen on.
  # Can be overriden by GRPC_PORT environment variable.
  # Default is 5050.
  port: 5050
  # useTls specifies whether to use TLS for the gRPC server.
  # Can be overriden by GRPC_USE_TLS environment variable.
  # Default is false.
  useTls: false
  # timeout is the timeout for gRPC requests.
  # Can be overriden by GRPC_TIMEOUT environment variable.
  # Default is 5s.
  timeout: 3s

# JWT tokens configuration.
tokens:
  # issuer is the issuer of the JWT tokens.
  # Can be overriden by TOKENS_ISSUER environment variable.
  issuer: sso.io
  # accessTtl is the time-to-live for access tokens.
  # Can be overriden by TOKENS_ACCESS_TTL environment variable.
  accessTtl: 5m
  # refreshTtl is the time-to-live for refresh tokens.
  # Can be overriden by TOKENS_REFRESH_TTL environment variable.
  refreshTtl: 240h
  # idTtl is the time-to-live for ID tokens.
  # Can be overriden by TOKENS_ID_TTL environment variable.
  idTtl: 24h
  emailVerificationTtl: 2h

# Limits configuration
limits:
  profile/password:
    # changeTimeout is the timeout for changing password.
    # Can be overriden by PASSWORD_CHANGE_TIMEOUT environment variable.
    # Default is 1h.
    changeTimeout: 1h
