secrets:
  postgresConn: #postgres://onny:4444@postgres:5432/onny
  # either an absolute or relative path to x509 server certificates.
  # Here it is as it is because of docker volume mounting
  # local directory configs mounts to /config directory inside a container
  tlsCertPath: /config/example-certs/server-key.pem
  tlsKeyPath: /config/example-certs/server-key.pem
  # but can be
  # tlsCertPath: ./example-certs/server-cert.pem
  # tlsKeyPath: ./example-certs/server-key.pem
http:
  port: 8080
  # does not work yet
  useTls: false
grpc:
  port: 5050
  # does not work yet
  useTls: false
  timeout: 3s
tokens:
  issuer: yoursso.com
  accessTtl: 5m
  refreshTtl: 240h
  idTtl: 5m