postgres_conn: postgres://user:12345678@postgres:5432/database
https:
  port: 8080
grpc:
  port: 5050
  timeout: 3s
tokens:
  issuer: yoursso.com
  access:
    ttl: 5m
  refresh:
    secret_path: example-certs/server-key.pem
    public_path: example-certs/server-key.pem
    ttl: 240h
  oauth_id:
    secret_path: example-certs/server-key.pem
    public_path: example-certs/server-key.pem
    ttl: 5m
  oauth_refresh:
    secret_path: example-certs/server-key.pem
    public_path: example-certs/server-key.pem
    ttl: 240h