// Code generated by mockery v2.45.0. DO NOT EDIT.

package appsmocks

import mock "github.com/stretchr/testify/mock"

// RandomGenerator is an autogenerated mock type for the RandomGenerator type
type RandomGenerator struct {
	mock.Mock
}

type RandomGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *RandomGenerator) EXPECT() *RandomGenerator_Expecter {
	return &RandomGenerator_Expecter{mock: &_m.Mock}
}

// RandomString provides a mock function with given fields:
func (_m *RandomGenerator) RandomString() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RandomString")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RandomGenerator_RandomString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RandomString'
type RandomGenerator_RandomString_Call struct {
	*mock.Call
}

// RandomString is a helper method to define mock.On call
func (_e *RandomGenerator_Expecter) RandomString() *RandomGenerator_RandomString_Call {
	return &RandomGenerator_RandomString_Call{Call: _e.mock.On("RandomString")}
}

func (_c *RandomGenerator_RandomString_Call) Run(run func()) *RandomGenerator_RandomString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RandomGenerator_RandomString_Call) Return(_a0 string, _a1 error) *RandomGenerator_RandomString_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RandomGenerator_RandomString_Call) RunAndReturn(run func() (string, error)) *RandomGenerator_RandomString_Call {
	_c.Call.Return(run)
	return _c
}

// NewRandomGenerator creates a new instance of RandomGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRandomGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *RandomGenerator {
	mock := &RandomGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
